extends Node

enum Resources {WOOD,ROCK,COIN,GOLD,DIAMOND}
enum Grounds {NATURE,MANMADE,WATER,SOLID,ALL}
enum BuildingType {RESOURCE,PRODUCER,DECORATION,MISC}

enum Powers {
	WOOD_CUTTER,
	STONE_CUTTER
}

